# Generated by Django 2.1.3 on 2019-01-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_mat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mat',
            name='company',
            field=models.SmallIntegerField(choices=[(0, '中兴'), (1, '京信'), (2, '三维'), (3, '华为'), (4, '烽火'), (5, '其他')], verbose_name='生产厂家'),
        ),
        migrations.AlterField(
            model_name='mat',
            name='major',
            field=models.SmallIntegerField(choices=[(0, '无线'), (1, '传输'), (2, '家宽'), (3, '土建'), (4, '电力')], verbose_name='专业类别'),
        ),
        migrations.AlterField(
            model_name='mat',
            name='mat_name',
            field=models.CharField(max_length=64, verbose_name='备件名称'),
        ),
    ]
